### ISSUE TITLE
OX_SECRETS_AWS_PROFILE_NAME

### ISSUE THREAD

**Issue by hxu-ids** [emin63/ox_secrets#1]
@emin63 
could you please make this read `os.environ`  just like other things in `setting.py`?

**Comment by hxu-ids** [comment]
ideally read it from env var `AWS_PROFILE` and fall back on `AWS_DEFAULT_PROFILE`. both are aws's invention. but the latter doesn't seem to work for me.

**Comment by emin63** [comment]
> ideally read it from env var `AWS_PROFILE` and fall back on `AWS_DEFAULT_PROFILE`. both are aws's invention. but the latter doesn't seem to work for me.

I don't think you want that. If you provide `AWS_PROFILE` as an environment variable then the low-level boto3 code should just use that. The only place `OX_SECRETS_AWS_PROFILE_NAME` is used is in https://github.com/emin63/ox_secrets/blob/93e501865686f97a120aaedd785451a290b56235/ox_secrets/core/aws.py#L34. The main use case for `OX_SECRETS_AWS_PROFILE_NAME` is if you want to override `AWS_PROFILE` env var or if you don't want to set the env var. If you are willing to set an env var, just set `AWS_PROFILE` and ignore `OX_SECRETS_AWS_PROFILE_NAME`.

Please re-open if I am confused about your request or use case.
