### ISSUE TITLE
OX_SECRETS_CATEGORY_REGEXP, OX_SECRETS_CATEGORY_REPLACE

### ISSUE THREAD

**Issue by hxu-ids** [emin63/ox_secrets#2]
@emin63 
You must be thinking about generic use cases when you added these two. 

Please consider a three level secret management:
* space, which is controlled by a single env var, values could be `prod`, `test`, `dev`, etc.
* category
* name

the code gets secret by specifying only the `category` and `name` but **not** the `space`, the implementation reads the env var for the `space` to look into.

This assumes different spaces have similar category-name structures, while the existing two env var solution allows for flexible category level.

**Comment by emin63** [comment]
This is a good point. The trouble is that it is not clear how the `space` should be used. For `category` and `name` most back-ends have a pretty natural interpretation (e.g., in AWS the `category` is the secret ID and the `name` is the value inside the secret data).

I think what you want is a prefix that always gets applied to category or something like that. For example, we could do the following:

  1. Have an `OX_SECRETS_SPACE` variable in `settings.py` which gets read from an env var (which defaults to empty string).
  2. In the `maybe_replace_category` method we first replace category with `OX_SECRETS_SPACE + category`, then apply `OX_SECRETS_CATEGORY_RE...`

See https://github.com/emin63/ox_secrets/blob/e33ba5aaa5cbf2716b52ea0b748fe2c1fd5f7794/ox_secrets/core/common.py#L131 for the `maybe_replace_category` method.

You could then set `OX_SECRETS_SPACE` env var to either `prod/` or `test/` depending on what you are trying to do.

Let me know if that addresses your use case and I'll make the change or let me know if you have a different use case in mind.

**Comment by hxu-ids** [comment]
* Let's park this for a while. I don't have blocking case at this point, see below.
* The case I want to have is to load multiple spaces with latter ones overwrite former ones. For example, 
  * I may want to load `tester` space followed by `hxu_personal_sandbox` space, to make sure I don't step into `prod` space by accident.
  * I now have a workaround to use 
    * `AWS_PROFILE=admin-henry `
    * `OX_SECRETS_CATEGORY_REGEXP='^prod/'`
    * `OX_SECRETS_CATEGORY_REPLACE='test/'`
